name: Weekly Crawl + Reindex

on:
  schedule:
    - cron: "0 3 * * 1" # Mondays 03:00 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Auth to GCP (use workload identity or a JSON key secret)
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Crawl Wyndham PDFs
        env:
          GCS_BUCKET: civreply-data
          DOCS_PREFIX: policies/wyndham/crawl
          CRAWL_BASE: https://www.wyndham.vic.gov.au
        run: python scripts/crawl_wyndham.py

      - name: Rebuild FAISS Index
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GCS_BUCKET: civreply-data
          COUNCIL_KEY: wyndham
        run: python -c "from app import rebuild_index_from_gcs; print(rebuild_index_from_gcs())"
