name: Wyndham nightly refresh

on:
  schedule:
    # 16:00 UTC ≈ 02:00 AEST (+/- DST). Adjust if you want.
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auth to GCP (service account JSON from secret)
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: |
          echo "$GCP_SA_JSON" > $HOME/gcs-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcs-key.json" >> $GITHUB_ENV

      - name: Run deep crawler -> uploads to GCS
        env:
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}   # e.g. civreply-data
          COUNCIL: wyndham
          DOC_PREFIX: policies/wyndham
          INCLUDE_IMAGES: "false"                 # set "true" if you want images
          HTTP_TIMEOUT: "25"
        run: |
          python -u wyndham_gcs_downloader_v2.py

      - name: (Optional) Rebuild FAISS index and upload
        if: ${{ vars.REBUILD_INDEX == 'true' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          COUNCIL: wyndham
          DOC_PREFIX: policies/wyndham
          INDEX_PREFIX: indexes/wyndham/faiss
        run: |
          python - <<'PY'
          import os
          from build_index_from_gcs import build  # if you kept a helper; else call inside app
          build()
          PY
